### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AnthonyRobert06**
Thanks for inviting me!

### CODE REVIEW

**Comment by Ian-Moffett** [comment]
> Thanks for inviting me!

No problem!

**Comment by AnthonyRobert06** [comment]
Oops made a mistake, sorry.

**Comment by Ian-Moffett** [comment]
> Oops made a mistake, sorry.

It's fine, I see it. I'll change it.

**Comment by Ian-Moffett** [comment]
Oh, you fixed it already.

**Review by Ian-Moffett — APPROVED** [review]

**Pull request merged**
